development:
  #adapter: mysql2
  #encoding: utf8
  #database: rouvignac_development
  #pool: 5
  #username: olivier
  #password:
  #host: 127.0.0.1
  #port: 3306
  adapter: sqlite3
  database: db/development.sqlite3
  pool: 5
  timeout: 5000
production:
  adapter: postgresql
  encoding: unicode
  database: rouvignac_production
  password:
  pool: 5
  timeout: 5000
  username:
  host: localhost
